---
title: "Exploratory Data Analysis"
author: "Beast"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: flatly
    toc: true
    number_sections: false
    toc_float:
      collapsed: false
      smooth_scroll: false
  pdf_document:
    toc: true
subtitle: Dalton & Madilin Super Document
mainfont: TimesNewRoman
sansfont: TimesNewRoman
monofont: TimesNewRoman
---

#### Load Relevant R Libraries
```{r warning=FALSE, message=FALSE}
library(rmarkdown); library(knitr); library(moments);library(mdsr) 
library(scatterplot3d); library(corrplot); library(pso);library(usethis)
library(psych); library(GPArotation); library(lavaan);library(here)
library(haven);library(tidyverse);library(tidyverse)
```

### Data Cleaning

#### Importing
```{r}
# Demographics
Demographics2011 <- read_xpt("Data 2011-12/DEMO_G.xpt") 
Demographics2013 <- read_xpt("Data 2013-14/DEMO_H.xpt") 
Demographics2015 <- read_xpt("Data 2015-16/DEMO_I.xpt")
Demographics2017 <- read_xpt("Data 2017-18/DEMO_J.xpt") 
Demographics2021 <- read_xpt("Data Aug2021-Aug2022/DEMO_L.xpt")
DemographicsPP2017 <- read_xpt("Data PP2017-20/P_DEMO.xpt")

# Examination
BloodPressure2011 <- read_xpt("Data 2011-12/BPX_G.xpt")
BloodPressure2013 <- read_xpt("Data 2013-14/BPX_H.xpt")
BloodPressure2015 <- read_xpt("Data 2015-16/BPX_I.xpt")
BloodPressure2017 <- read_xpt("Data 2017-18/BPX_J.xpt")
BloodPressure2021 <- read_xpt("Data Aug2021-Aug2022/BPXO_L.xpt")
BloodPressureP2017 <- read_xpt("Data PP2017-20/P_BPXO.xpt")

BodyMeasurements2011 <- read_xpt("Data 2011-12/BMX_G.xpt")
BodyMeasurements2013 <- read_xpt("Data 2013-14/BMX_H.xpt")
BodyMeasurements2015 <- read_xpt("Data 2015-16/BMX_I.xpt")
BodyMeasurements2017 <- read_xpt("Data 2017-18/BMX_J.xpt")
BodyMeasurements2021 <- read_xpt("Data Aug2021-Aug2022/BMX_L.xpt")
BodyMeasurementsP2017 <- read_xpt("Data PP2017-20/P_BMX.xpt")

# Lab
TotalChol2011 <- read_xpt("Data 2011-12/TCHOL_G.xpt")
TotalChol2013 <- read_xpt("Data 2013-14/TCHOL_H.xpt")
TotalChol2015 <- read_xpt("Data 2015-16/TCHOL_I.xpt")
TotalChol2017 <- read_xpt("Data 2017-18/TCHOL_J.xpt")
TotalChol2021 <- read_xpt("Data Aug2021-Aug2022/TCHOL_L.xpt")
TotalCholP2017 <- read_xpt("Data PP2017-20/P_TCHOL.xpt")

HDL_Chol2011 <- read_xpt("Data 2011-12/HDL_G.xpt")
HDL_Chol2013 <- read_xpt("Data 2013-14/HDL_H.xpt")
HDL_Chol2015 <- read_xpt("Data 2015-16/HDL_I.xpt")
HDL_Chol2017 <- read_xpt("Data 2017-18/HDL_J.xpt")
HDL_Chol2021 <- read_xpt("Data Aug2021-Aug2022/HDL_L.xpt")
HDL_CholP2017 <- read_xpt("Data PP2017-20/P_HDL.xpt")

LDL_Tri_Chol2011 <-read_xpt("Data 2011-12/TRIGLY_G.xpt")
LDL_Tri_Chol2013 <-read_xpt("Data 2013-14/TRIGLY_H.xpt")
LDL_Tri_Chol2015 <-read_xpt("Data 2015-16/TRIGLY_I.xpt")
LDL_Tri_Chol2017 <-read_xpt("Data 2017-18/TRIGLY_J.xpt")
LDL_Tri_Chol2021 <-read_xpt("Data Aug2021-Aug2022/TRIGLY_L.xpt")
LDL_Tri_CholP2017 <-read_xpt("Data PP2017-20/P_TRIGLY.xpt")

GLYP2013 <- read_xpt("Data 2013-14/SSGLYP_H.xpt")
GLYP2015 <- read_xpt("Data 2015-16/SSGLYP_I.xpt")
GLYP2017 <- read_xpt("Data 2017-18/SSGLYP_J.xpt")

Insulin2013 <- read_xpt("Data 2013-14/INS_H.xpt")
Insulin2015 <- read_xpt("Data 2015-16/INS_I.xpt")
Insulin2017 <- read_xpt("Data 2017-18/INS_J.xpt")
Insulin2021 <- read_xpt("Data Aug2021-Aug2022/INS_L.xpt")
InsulinP2017 <- read_xpt("Data PP2017-20/P_INS.xpt")

Metals2011 <-read_xpt("Data 2011-12/UHM_G.xpt")
Metals2013 <-read_xpt("Data 2013-14/UM_H.xpt")
Metals2015 <-read_xpt("Data 2015-16/UM_I.xpt")
Metals2017 <-read_xpt("Data 2017-18/UM_J.xpt")
Metals2021 <-read_xpt("Data Aug2021-Aug2022/PBCD_L.xpt")
MetalsP2017 <-read_xpt("Data PP2017-20/P_UM.xpt")

PFAs2011 <-read_xpt("Data 2011-12/PFC_G.xpt")
PFAs2013 <-read_xpt("Data 2013-14/SSPFSU_H.xpt")
PFAs2015 <-read_xpt("Data 2015-16/PFAS_I.xpt")
PFAs2017 <-read_xpt("Data 2017-18/PFAS_J.xpt")
PFAsP2017 <-read_xpt("Data PP2017-20/P_PFAS.xpt")

Hormones2011 <- read_xpt("Data 2011-12/TST_G.xpt")
Hormones2013 <- read_xpt("Data 2013-14/TST_H.xpt")
Hormones2015 <- read_xpt("Data 2015-16/TST_I.xpt")
Hormones2017 <- read_xpt("Data 2017-18/SSTST_J.xpt")
Hormones2021 <- read_xpt("Data Aug2021-Aug2022/TST_L.xpt")
HormonesP2017 <- read_xpt("Data PP2017-20/P_TST.xpt")

# Questionnaire 
DiabetesQ2011 <- read_xpt("Data 2011-12/DIQ_G.xpt")
DiabetesQ2013 <- read_xpt("Data 2013-14/DIQ_H.xpt")
DiabetesQ2015 <- read_xpt("Data 2015-16/DIQ_I.xpt")
DiabetesQ2017 <- read_xpt("Data 2017-18/DIQ_J.xpt")
DiabetesQ2021 <- read_xpt("Data Aug2021-Aug2022/DIQ_L.xpt")
DiabetesQP2017 <- read_xpt("Data PP2017-20/P_DIQ.xpt")

IncomeQ2011 <- read_xpt("Data 2011-12/INQ_G.xpt")
IncomeQ2013 <- read_xpt("Data 2013-14/INQ_H.xpt")
IncomeQ2015 <- read_xpt("Data 2015-16/INQ_I.xpt")
IncomeQ2017 <- read_xpt("Data 2017-18/INQ_J.xpt")
IncomeQ2021 <- read_xpt("Data Aug2021-Aug2022/INQ_L.xpt")
IncomeQP2017 <- read_xpt("Data PP2017-20/P_INQ.xpt")

MedicalCondnsQ2011 <- read_xpt("Data 2011-12/MCQ_G.xpt")
MedicalCondnsQ2013 <- read_xpt("Data 2013-14/MCQ_H.xpt")
MedicalCondnsQ2015 <- read_xpt("Data 2015-16/MCQ_I.xpt")
MedicalCondnsQ2017 <- read_xpt("Data 2017-18/MCQ_J.xpt")
MedicalCondnsQ2021 <- read_xpt("Data Aug2021-Aug2022/MCQ_L.xpt")
MedicalCondnsQP2017 <- read_xpt("Data PP2017-20/P_MCQ.xpt")

MentalHealthQ2011 <- read_xpt("Data 2011-12/DPQ_G.xpt")
MentalHealthQ2013 <- read_xpt("Data 2013-14/DPQ_H.xpt")
MentalHealthQ2015 <- read_xpt("Data 2015-16/DPQ_I.xpt")
MentalHealthQ2017 <- read_xpt("Data 2017-18/DPQ_J.xpt")
MentalHealthQ2021 <- read_xpt("Data Aug2021-Aug2022/DPQ_L.xpt")
MentalHealthQP2017 <- read_xpt("Data PP2017-20/P_DPQ.xpt")

PestisideQ2011 <- read_xpt("Data 2011-12/PUQMEC_G.xpt")
PestisideQ2013 <- read_xpt("Data 2013-14/PUQMEC_H.xpt")
PestisideQ2015 <- read_xpt("Data 2015-16/PUQMEC_I.xpt")
PestisideQ2017 <- read_xpt("Data 2017-18/PUQMEC_J.xpt")
PestisideQ2021 <- read_xpt("Data Aug2021-Aug2022/PUQMEC_L.xpt")
PestisideQP2017 <- read_xpt("Data PP2017-20/P_PUQMEC.xpt")

PhysicalActQ2011 <- read_xpt("Data 2011-12/PAQ_G.xpt")
PhysicalActQ2013 <- read_xpt("Data 2013-14/PAQ_H.xpt")
PhysicalActQ2015 <- read_xpt("Data 2015-16/PAQ_I.xpt")
PhysicalActQ2017 <- read_xpt("Data 2017-18/PAQ_J.xpt")
PhysicalActQ2021 <- read_xpt("Data Aug2021-Aug2022/PAQ_L.xpt")
PhysicalActQP2017 <- read_xpt("Data PP2017-20/P_PAQ.xpt")

PrescriptionMedsQ2011 <- read_xpt("Data 2011-12/RXQ_RX_G.xpt")
PrescriptionMedsQ2013 <- read_xpt("Data 2013-14/RXQ_RX_H.xpt")
PrescriptionMedsQ2015 <- read_xpt("Data 2015-16/RXQ_RX_I.xpt")
PrescriptionMedsQ2017 <- read_xpt("Data 2017-18/RXQ_RX_J.xpt")
PrescriptionMedsQ2021 <- read_xpt("Data Aug2021-Aug2022/RXQ_RX_L.xpt")
PrescriptionMedsQP2017 <- read_xpt("Data PP2017-20/P_RXQ_RX.xpt")

SleepDisordersQ2011 <- read_xpt("Data 2011-12/SLQ_G.xpt")
SleepDisordersQ2013 <- read_xpt("Data 2013-14/SLQ_H.xpt")
SleepDisordersQ2015 <- read_xpt("Data 2015-16/SLQ_I.xpt")
SleepDisordersQ2017 <- read_xpt("Data 2017-18/SLQ_J.xpt")
SleepDisordersQ2021 <- read_xpt("Data Aug2021-Aug2022/SLQ_L.xpt")
SleepDisordersQP2017 <- read_xpt("Data PP2017-20/P_SLQ.xpt")

SmokingQ2011 <- read_xpt("Data 2011-12/SMQ_G.xpt")
SmokingQ2013 <- read_xpt("Data 2013-14/SMQ_H.xpt")
SmokingQ2015 <- read_xpt("Data 2015-16/SMQ_I.xpt")
SmokingQ2017 <- read_xpt("Data 2017-18/SMQ_J.xpt")
SmokingQ2021 <- read_xpt("Data Aug2021-Aug2022/SMQ_L.xpt")
SmokingQP2017 <- read_xpt("Data PP2017-20/P_SMQ.xpt")

WeightHistoryQ2011 <- read_xpt("Data 2011-12/WHQ_G.xpt")
WeightHistoryQ2013 <- read_xpt("Data 2013-14/WHQ_H.xpt")
WeightHistoryQ2015 <- read_xpt("Data 2015-16/WHQ_I.xpt")
WeightHistoryQ2017 <- read_xpt("Data 2017-18/WHQ_J.xpt")
WeightHistoryQ2021 <- read_xpt("Data Aug2021-Aug2022/WHQ_L.xpt")
WeightHistoryQP2017 <- read_xpt("Data PP2017-20/P_WHQ.xpt")

YouthWeightHistoryQ2011 <- read_xpt("Data 2011-12/WHQMEC_G.xpt")
YouthWeightHistoryQ2015 <- read_xpt("Data 2015-16/WHQMEC_I.xpt")
YouthWeightHistoryQ2017 <- read_xpt("Data 2017-18/WHQMEC_J.xpt")
YouthWeightHistoryQP2017 <- read_xpt("Data PP2017-20/P_WHQMEC.xpt")
```

#### Cleaning
```{r}
# Demographics
Demographics2011 <- Demographics2011 |>
  select("SEQN", "RIDSTATR", "RIAGENDR","RIDAGEYR", "RIDRETH3")
Demographics2013 <- Demographics2013 |>
  select("SEQN", "RIDSTATR", "RIAGENDR","RIDAGEYR", "RIDRETH3")
Demographics2015 <- Demographics2015 |>
  select("SEQN", "RIDSTATR", "RIAGENDR","RIDAGEYR", "RIDRETH3")
Demographics2017 <- Demographics2017 |>
  select("SEQN", "RIDSTATR", "RIAGENDR","RIDAGEYR", "RIDRETH3")
Demographics2021 <- Demographics2021 |>
  select("SEQN", "RIDSTATR", "RIAGENDR","RIDAGEYR", "RIDRETH3")
DemographicsPP2017 <- DemographicsPP2017 |>
  select("SEQN", "RIDSTATR", "RIAGENDR","RIDAGEYR", "RIDRETH3")

# Examination
BloodPressure2011 <- BloodPressure2011 |>
  select("SEQN", "PEASCST1", "PEASCTM1", "BPXCHR", "BPQ150A", "BPQ150B", "BPQ150C", "BPQ150D", "BPXPLS", "BPXPULS", "BPXPTY",  "BPXSY1", "BPXSY2", "BPXSY3", "BPXSY4", "BPXDI1", "BPXDI2", "BPXDI3", "BPXDI4")
BloodPressure2013 <- BloodPressure2013 |>
  select("SEQN", "PEASCST1", "PEASCTM1", "BPXCHR", "BPXPLS", "BPXPULS", "BPXPTY",  "BPXSY1", "BPXSY2", "BPXSY3", "BPXSY4", "BPXDI1", "BPXDI2", "BPXDI3", "BPXDI4")
BloodPressure2015 <- BloodPressure2015 |>
  select("SEQN", "BPXCHR", "BPXPULS", "BPXSY1","BPXSY2","BPXSY3", "BPXSY4", "BPXDI1", "BPXDI2", "BPXDI3", "BPXDI4")
BloodPressure2017 <- BloodPressure2017 |>
  select("SEQN", "BPXCHR", "BPXPULS", "BPXSY1","BPXSY2","BPXSY3", "BPXSY4", "BPXDI1", "BPXDI2", "BPXDI3", "BPXDI4")
BloodPressure2021 <- BloodPressure2021 |>
  select("SEQN", "BPXOSY1", "BPXOSY2", "BPXOSY3", "BPXODI1", "BPXODI2",  "BPXODI3", "BPXOPLS1", "BPXOPLS2", "BPXOPLS3")
BloodPressureP2017 <- BloodPressureP2017 |>
  select("SEQN", "BPXOSY1", "BPXOSY2",  "BPXOSY3", "BPXODI1", "BPXODI2", "BPXODI3", "BPXOPLS1", "BPXOPLS2", "BPXOPLS3")

BodyMeasurements2011 <- BodyMeasurements2011 |>
  select("SEQN", "BMXWT",  "BMXBMI",  "BMXHT",  "BMXWAIST", "BMXSAD1", "BMXSAD2", "BMXSAD3", "BMXSAD4")
BodyMeasurements2013 <- BodyMeasurements2013 |>
  select("SEQN","BMXWT",  "BMXBMI",  "BMXHT",  "BMXWAIST", "BMXSAD1", "BMXSAD2", "BMXSAD3", "BMXSAD4")
BodyMeasurements2015 <- BodyMeasurements2015 |>
  select("SEQN","BMXWT",  "BMXBMI",  "BMXHT",  "BMXWAIST", "BMXSAD1", "BMXSAD2", "BMXSAD3", "BMXSAD4")
BodyMeasurements2017 <- BodyMeasurements2017 |>
  select("SEQN","BMXWT", "BMXHT", "BMXBMI", "BMXWAIST")
BodyMeasurements2021 <- BodyMeasurements2021 |>
  select("SEQN","BMXWT", "BMXHT", "BMXBMI", "BMXWAIST")
BodyMeasurementsP2017 <- BodyMeasurementsP2017 |>
  select("SEQN","BMXWT", "BMXHT", "BMXBMI", "BMXWAIST")

# Lab
TotalChol2011 <- TotalChol2011 |>
  select("SEQN", "LBXTC", "LBDTCSI")
TotalChol2013 <- TotalChol2013 |>
  select("SEQN", "LBXTC", "LBDTCSI")
TotalChol2015 <- TotalChol2015 |>
  select("SEQN", "LBXTC", "LBDTCSI")
TotalChol2017 <- TotalChol2017 |>
  select("SEQN", "LBXTC", "LBDTCSI")
TotalChol2021 <- TotalChol2021 |>
  select("SEQN", "LBXTC", "LBDTCSI","WTPH2YR")
TotalCholP2017 <- TotalCholP2017 |>
  select("SEQN", "LBXTC", "LBDTCSI")

HDL_Chol2011 <- HDL_Chol2011|>
  select("SEQN", "LBDHDD", "LBDHDDSI")
HDL_Chol2013 <- HDL_Chol2013 |>
  select("SEQN", "LBDHDD", "LBDHDDSI")
HDL_Chol2015 <- HDL_Chol2015 |>
  select("SEQN", "LBDHDD", "LBDHDDSI")
HDL_Chol2017 <- HDL_Chol2017 |>
  select("SEQN", "LBDHDD", "LBDHDDSI")
HDL_Chol2021 <- HDL_Chol2021 |>
  select("SEQN","LBDHDD", "LBDHDDSI")
HDL_CholP2017 <- HDL_CholP2017 |>
  select("SEQN", "LBDHDD", "LBDHDDSI")

LDL_Tri_Chol2011 <- LDL_Tri_Chol2011 |>
  select("SEQN", "WTSAF2YR", "LBXTR","LBDTRSI","LBDLDL","LBDLDLSI")
LDL_Tri_Chol2013 <- LDL_Tri_Chol2013 |>
  select("SEQN", "WTSAF2YR" ,"LBXTR","LBDTRSI","LBDLDL","LBDLDLSI")
LDL_Tri_Chol2015 <- LDL_Tri_Chol2015 |>
  select("SEQN", "WTSAF2YR", "LBXTR", "LBDTRSI", "LBDLDL","LBDLDLSI")
LDL_Tri_Chol2017 <- LDL_Tri_Chol2017 |>
  select("SEQN", "WTSAF2YR", "LBXTR", "LBDTRSI", "LBDLDL", "LBDLDLSI", "LBDLDLM", "LBDLDMSI", "LBDLDLN", "LBDLDNSI")
LDL_Tri_Chol2021 <- LDL_Tri_Chol2021 |>
  select("SEQN", "WTSAF2YR","LBXTLG", "LBDTRSI", "LBDLDL", "LBDLDLSI","LBDLDLM","LBDLDMSI","LBDLDLN","LBDLDNSI")
LDL_Tri_CholP2017 <- LDL_Tri_CholP2017 |>
  select("SEQN", "WTSAFPRP", "LBXTR", "LBDTRSI", "LBDLDL","LBDLDLSI","LBDLDLM", "LBDLDMSI","LBDLDLN", "LBDLDNSI")

GLYP2013 <- GLYP2013 |>
  select("SEQN", "WTSSCH2Y","SSGLYP","SSGLYPL")
GLYP2015 <- GLYP2015 |>
  select("SEQN", "WTSSGL2Y","SSGLYP","SSGLYP")
GLYP2017 <- GLYP2017 |>
  select("SEQN", "WTSSBJ2Y", "SSGLYP","SSGLYPL")

Insulin2013 <- Insulin2013 |>
  select("SEQN", "LBXIN", "LBDINSI", "PHAFSTMN")
Insulin2015 <- Insulin2015 |>
  select("SEQN", "LBXIN", "LBDINSI", "PHAFSTMN")
Insulin2017 <- Insulin2017 |>
  select("SEQN", "LBXIN", "LBDINSI")
Insulin2021 <- Insulin2021 |>
  select("SEQN", "LBXIN", "LBDINSI")
InsulinP2017 <- InsulinP2017 |>
  select("SEQN", "LBXIN","LBDINSI","LBDINLC")

#Metals2011 <- Metals2011 |>
#  select("SEQN")
#Metals2013 <- Metals2013 |>
#  select("SEQN")
#Metals2015 <- Metals2015 |>
#  select("SEQN")
#Metals2017 <- Metals2017 |>
#  select("SEQN")
#Metals2021 <- Metals2021 |>
#  select("SEQN")
#MetalsP2017 <- MetalsP2017 |>
#  select("SEQN")

PFAs2011 <- PFAs2011 |>
  select("SEQN", "LBXPFOS", "LBXPFOA", "LBXPFHS","LBXPFNA")
PFAs2013 <- PFAs2013 |>
  select("SEQN", "SSNFOS", "SSMFOS", "SSNFOA", "SSBFOA", "SSPFNA", "SSPFHS")
PFAs2015 <- PFAs2015 |>
  select("SEQN", "LBXNFOS","LBXMFOS", "LBXNFOA","LBXBFOA", "LBXPFHS", "LBXPFNA")
PFAs2017 <- PFAs2017 |>
  select("SEQN", "LBXNFOS", "LBXMFOS", "LBXNFOA", "LBXBFOA", "LBXPFHS", "LBXPFNA")
PFAsP2017 <- PFAsP2017 |>
  select("SEQN", "LBXNFOS", "LBXMFOS", "LBXNFOA", "LBXBFOA", "LBXPFHS", "LBXPFNA")

Hormones2011 <- Hormones2011 |>
  select("SEQN", "LBXTST")
Hormones2013 <- Hormones2013 |>
  select("SEQN", "LBXTST","LBXEST","LBXSHBG")
Hormones2015 <- Hormones2015 |>
  select("SEQN", "LBXTST","LBXEST","LBXSHBG")
Hormones2017 <- Hormones2017 |>
  select("SEQN", "SSTEST", "SSTSHBG", "SSTLUH")
Hormones2021 <- Hormones2021 |>
  select("SEQN", "LBXEST", "LBXSHBG", "LBXLUH" , "LBXTST")
HormonesP2017 <- HormonesP2017 |>
  select("SEQN", "LBXEST", "LBXSHBG", "LBXLUH")

# Questionnaire 
DiabetesQ2011 <- DiabetesQ2011 |>
  select("SEQN", "DIQ010", "DIQ160")
DiabetesQ2013 <- DiabetesQ2013 |>
  select("SEQN", "DIQ010", "DIQ160")
DiabetesQ2015 <- DiabetesQ2015 |>
  select("SEQN", "DIQ010", "DIQ160")
DiabetesQ2017 <- DiabetesQ2017 |>
  select("SEQN", "DIQ010", "DIQ160")
DiabetesQ2021 <- DiabetesQ2021 |>
  select("SEQN", "DIQ010", "DIQ160")
DiabetesQP2017 <- DiabetesQP2017 |>
  select("SEQN", "DIQ010", "DIQ160")

IncomeQ2011 <- IncomeQ2011 |>
  select("SEQN", "INQ020", "INQ012", "INQ030", "INQ060")
IncomeQ2013 <- IncomeQ2013 |>
  select("SEQN", "INQ020", "INQ012", "INQ030", "INQ060")
IncomeQ2015 <- IncomeQ2015 |>
  select("SEQN", "INQ020", "INQ012", "INQ030", "INQ060")
IncomeQ2017 <- IncomeQ2017 |>
  select("SEQN", "INQ020", "INQ012", "INQ030", "INQ060")
IncomeQ2021 <- IncomeQ2021 |>
  select("SEQN", "INDFMMPI", "INDFMMPC")
IncomeQP2017 <- IncomeQP2017 |>
  select("SEQN", "INDFMMPI", "INDFMMPC")

MedicalCondnsQ2011 <- MedicalCondnsQ2011 |>
  select("SEQN", "MCQ010", "MCQ053", "MCQ160A", "MCQ160B", "MCQ160C", "MCQ160D", "MCQ160E", "MCQ160F", "MCQ160M", "MCQ160L", "MCQ220","MCQ230A", "MCQ230B", "MCQ230C", "MCQ230D")
MedicalCondnsQ2013 <- MedicalCondnsQ2013 |>
  select("SEQN", "MCQ010", "AGQ030", "MCQ053", "MCQ070", "MCQ082", "MCQ084", "MCQ084", "MCQ160A", "MCQ160N", "MCQ160B", "MCQ160C", "MCQ160D", "MCQ160E", "MCQ160F", "MCQ160G", "MCQ160M", "MCQ160K", "MCQ170K", "MCQ160L", "MCQ160O", "MCQ203", "MCQ220", "MCQ230A", "MCQ230B", "MCQ230C", "MCQ365A", "MCQ365B", "MCQ365C", "MCQ365D")
MedicalCondnsQ2015 <- MedicalCondnsQ2015 |>
  select("SEQN", "MCQ010", "AGQ030", "MCQ053", "MCQ160A", "MCQ160N", "MCQ160B", "MCQ160C", "MCQ160D", "MCQ160E", "MCQ160F", "MCQ160G", "MCQ160M", "MCQ160K", "MCQ160L", "MCQ160O", "MCQ220", "MCQ230A", "MCQ230B", "MCQ230C", "MCQ230D", "MCQ365A", "MCQ365B", "MCQ365C", "MCQ365D")
MedicalCondnsQ2017 <- MedicalCondnsQ2017 |>
  select("SEQN", "MCQ010", "AGQ030", "MCQ053", "MCQ160A", "MCQ160N", "MCQ160B", "MCQ160C", "MCQ160D", "MCQ160E", "MCQ160F", "MCQ160M", "MCQ160G", "MCQ160K", "MCQ160O", "MCQ160L", "MCQ500", "MCQ550", "MCQ203", "MCQ220", "MCQ230A", "MCQ230B", "MCQ230C","MCQ366A", "MCQ366B", "MCQ366C", "MCQ366D")
MedicalCondnsQ2021 <- MedicalCondnsQ2021 |>
  select("SEQN", "MCQ010", "AGQ030", "MCQ053", "MCQ160A", "MCQ160B", "MCQ160C", "MCQ160D","MCQ160E", "MCQ160F", "MCQ160M", "MCQ160P", "MCQ160L", "MCQ500", "MCQ550", "MCQ220", "MCQ230A", "MCQ230B", "MCQ230C")
MedicalCondnsQP2017 <- MedicalCondnsQP2017 |>
  select("SEQN", "MCQ010", "AGQ030", "MCQ053", "MCQ160A", "MCQ195", "MCQ160B", "MCD180B", "MCQ160C", "MCQ160D", "MCQ160E", "MCQ160F", "MCQ160M", "MCQ160P", "MCQ160L", "MCQ500", "MCQ550", "MCQ220", "MCQ230A", "MCQ230B", "MCQ230C", "MCQ366A", "MCQ366B", "MCQ366C", "MCQ366D")

MentalHealthQ2011 <- MentalHealthQ2011 |>
  select("SEQN", "DPQ010", "DPQ020", "DPQ030", "DPQ040","DPQ050", "DPQ060", "DPQ070", "DPQ080", "DPQ090", "DPQ100")
MentalHealthQ2013 <- MentalHealthQ2013 |>
  select("SEQN", "DPQ010", "DPQ020", "DPQ030", "DPQ040","DPQ050", "DPQ060", "DPQ070", "DPQ080", "DPQ090", "DPQ100")
MentalHealthQ2015 <- MentalHealthQ2015 |>
  select("SEQN", "DPQ010", "DPQ020", "DPQ030", "DPQ040","DPQ050", "DPQ060", "DPQ070", "DPQ080", "DPQ090", "DPQ100")
MentalHealthQ2017 <- MentalHealthQ2017 |>
  select("SEQN", "DPQ010", "DPQ020", "DPQ030", "DPQ040","DPQ050", "DPQ060", "DPQ070", "DPQ080", "DPQ090", "DPQ100")
MentalHealthQ2021 <- MentalHealthQ2021 |>
  select("SEQN", "DPQ010", "DPQ020", "DPQ030", "DPQ040","DPQ050", "DPQ060", "DPQ070", "DPQ080", "DPQ090", "DPQ100")
MentalHealthQP2017 <- MentalHealthQP2017 |>
  select("SEQN", "DPQ010", "DPQ020", "DPQ030", "DPQ040","DPQ050", "DPQ060", "DPQ070", "DPQ080", "DPQ090", "DPQ100")

PestisideQ2011 <- PestisideQ2011 |>
  select("SEQN", "PUQ100", "PUQ110")
PestisideQ2013 <- PestisideQ2013 |>
  select("SEQN", "PUQ100", "PUQ110")
PestisideQ2015 <- PestisideQ2015 |>
  select("SEQN", "PUQ100", "PUQ110")
PestisideQ2017 <- PestisideQ2017 |>
  select("SEQN", "PUQ100", "PUQ110")
PestisideQ2021 <- PestisideQ2021 |>
  select("SEQN", "PUQ100", "PUQ110")
PestisideQP2017 <- PestisideQP2017 |>
  select("SEQN", "PUQ100", "PUQ110")

PhysicalActQ2011 <- PhysicalActQ2011 |>
  select("SEQN", "PAQ706", "PAQ610", "PAQ625", "PAQ650", "PAQ655", "PAQ665", "PAQ670", "PAQ710", "PAQ715")
PhysicalActQ2013 <- PhysicalActQ2013 |>
  select("SEQN", "PAQ610", "PAQ625", "PAQ650", "PAQ655", "PAQ665", "PAQ670", "PAQ710", "PAQ715", "PAQ706")
PhysicalActQ2015 <- PhysicalActQ2015 |>
  select("SEQN", "PAQ610", "PAQ625", "PAQ650", "PAQ655", "PAQ665", "PAQ670", "PAQ710", "PAQ715", "PAQ706")
PhysicalActQ2017 <- PhysicalActQ2017 |>
  select("SEQN", "PAQ610", "PAQ625", "PAQ650", "PAQ655", "PAQ665", "PAQ670")
PhysicalActQ2021 <- PhysicalActQ2021 |>
  select("SEQN", "PAD790Q", "PAD790U", "PAD680")
PhysicalActQP2017 <- PhysicalActQP2017 |>
  select("SEQN", "PAQ610", "PAQ625", "PAQ650", "PAQ655", "PAQ665", "PAQ670")

PrescriptionMedsQ2011 <- PrescriptionMedsQ2011 |>
  select("SEQN", "RXDUSE","RXDDRUG","RXDDRGID","RXQSEEN","RXDDAYS","RXDCOUNT")
PrescriptionMedsQ2013 <- PrescriptionMedsQ2013 |>
  select("SEQN", "RXDUSE","RXDDRUG","RXDDRGID","RXQSEEN","RXDDAYS")
PrescriptionMedsQ2015 <- PrescriptionMedsQ2015 |>
  select("SEQN", "RXDUSE","RXDDRUG","RXDDRGID","RXQSEEN","RXDDAYS","RXDCOUNT")
PrescriptionMedsQ2017 <- PrescriptionMedsQ2017 |>
  select("SEQN", "RXDUSE","RXDDRUG","RXDDRGID","RXQSEEN","RXDDAYS","RXDCOUNT")
PrescriptionMedsQ2021 <- PrescriptionMedsQ2021 |>
  select("SEQN", "RXQ033","RXQ050")
PrescriptionMedsQP2017 <- PrescriptionMedsQP2017 |>
  select("SEQN", "RXDUSE","RXDDRUG","RXDDRGID","RXQSEEN","RXDDAYS","RXDCOUNT")

SleepDisordersQ2011 <- SleepDisordersQ2011 |>
  select("SEQN", "SLD010H", "SLQ050", "SLQ060")
SleepDisordersQ2013 <- SleepDisordersQ2013 |>
  select("SEQN", "SLD010H", "SLQ050", "SLQ060")
SleepDisordersQ2015 <- SleepDisordersQ2015 |>
  select("SEQN", "SLD012", "SLQ040", "SLQ050", "SLQ120", "SLQ030")
SleepDisordersQ2017 <- SleepDisordersQ2017 |>
  select("SEQN", "SLD012", "SLD013","SLQ030","SLQ040","SLQ050","SLQ120")
SleepDisordersQ2021 <- SleepDisordersQ2021 |>
  select("SEQN", "SLD012", "SLQ320", "SLD013")
SleepDisordersQP2017 <- SleepDisordersQP2017 |>
  select("SEQN", "SLD012", "SLQ320", "SLD013", "SLQ030","SLQ040","SLQ050","SLQ120")

SmokingQ2011 <- SmokingQ2011 |>
  select("SEQN", "SMD030", "SMQ040", "SMD650", "SMD100MN")
SmokingQ2013 <- SmokingQ2013 |>
  select("SEQN", "SMD030", "SMQ040", "SMD650", "SMD100MN")
SmokingQ2015 <- SmokingQ2015 |>
  select("SEQN", "SMD030", "SMQ040", "SMD650", "SMD100MN")
SmokingQ2017 <- SmokingQ2017 |>
  select("SEQN", "SMD030", "SMQ040", "SMD650", "SMD100MN")
SmokingQ2021 <- SmokingQ2021 |>
  select("SEQN", "SMQ040", "SMD650", "SMD100MN")
SmokingQP2017 <- SmokingQP2017 |>
  select("SEQN", "SMD030", "SMQ040", "SMD650", "SMD100MN")

WeightHistoryQ2011 <- WeightHistoryQ2011 |>
  select("SEQN", "WHD080E", "WHD080B", "WHD080I", "WHD100R", "WHQ150")
WeightHistoryQ2013 <- WeightHistoryQ2013 |>
  select("SEQN", "WHD080E", "WHD080B", "WHD080I", "WHQ150")
WeightHistoryQ2015 <- WeightHistoryQ2015 |>
  select("SEQN", "WHD080E", "WHD080B", "WHD080I", "WHQ150")
WeightHistoryQ2017 <- WeightHistoryQ2017 |>
  select("SEQN", "WHD080E", "WHD080B", "WHD080I", "WHQ150")
WeightHistoryQ2021 <- WeightHistoryQ2021 |>
  select("SEQN", "WHQ070")
WeightHistoryQP2017 <- WeightHistoryQP2017 |>
  select("SEQN", "WHD080E", "WHD080B", "WHD080I", "WHQ150")
```

#### Merging
```{r}
# Examination
Examination2011 <- BodyMeasurements2011 |>
  full_join(BloodPressure2011, by = c("SEQN" = "SEQN"))

Examination2013 <- BodyMeasurements2013 |>
  full_join(BloodPressure2013, by = c("SEQN" = "SEQN"))

Examination2015 <- BodyMeasurements2015 |>
  full_join(BloodPressure2015, by = c("SEQN" = "SEQN"))

Examination2017 <- BodyMeasurements2017 |>
  full_join(BloodPressure2017, by = c("SEQN" = "SEQN"))

Examination2021 <- BodyMeasurements2021 |>
  full_join(BloodPressure2021, by = c("SEQN" = "SEQN"))

ExaminationP2017 <- BodyMeasurementsP2017 |>
  full_join(BloodPressureP2017, by = c("SEQN" = "SEQN"))

# Lab
Lab2011 <- TotalChol2011 |>
  full_join(HDL_Chol2011, by = c("SEQN" = "SEQN")) |>
  full_join(LDL_Tri_Chol2011, by = c("SEQN" = "SEQN")) |>
  full_join(PFAs2011, by = c("SEQN" = "SEQN")) |>
  full_join(Hormones2011, by = c("SEQN" = "SEQN"))

Lab2013 <- TotalChol2013 |>
  full_join(HDL_Chol2013, by = c("SEQN" = "SEQN")) |>
  full_join(LDL_Tri_Chol2013, by = c("SEQN" = "SEQN")) |>
  full_join(GLYP2013, by = c("SEQN" = "SEQN")) |>
  full_join(Insulin2013, by = c("SEQN" = "SEQN")) |>
  full_join(PFAs2013, by = c("SEQN" = "SEQN")) |>
  full_join(Hormones2013, by = c("SEQN" = "SEQN"))

Lab2015 <- TotalChol2015 |>
  full_join(HDL_Chol2015, by = c("SEQN" = "SEQN")) |>
  full_join(LDL_Tri_Chol2015, by = c("SEQN" = "SEQN")) |>
  full_join(GLYP2015, by = c("SEQN" = "SEQN")) |>
  full_join(Insulin2015, by = c("SEQN" = "SEQN")) |>
  full_join(PFAs2015, by = c("SEQN" = "SEQN")) |>
  full_join(Hormones2015, by = c("SEQN" = "SEQN"))

Lab2017 <- TotalChol2017 |>
  full_join(HDL_Chol2017, by = c("SEQN" = "SEQN")) |>
  full_join(LDL_Tri_Chol2017, by = c("SEQN" = "SEQN")) |>
  full_join(GLYP2017, by = c("SEQN" = "SEQN")) |>
  full_join(Insulin2017, by = c("SEQN" = "SEQN")) |>
  full_join(PFAs2017, by = c("SEQN" = "SEQN")) |>
  full_join(Hormones2017, by = c("SEQN" = "SEQN"))

Lab2021 <- TotalChol2021 |>
  full_join(HDL_Chol2021, by = c("SEQN" = "SEQN")) |>
  full_join(LDL_Tri_Chol2021, by = c("SEQN" = "SEQN")) |>
  full_join(Insulin2021, by = c("SEQN" = "SEQN")) |>
  full_join(Hormones2021, by = c("SEQN" = "SEQN"))

LabP2017 <- TotalCholP2017 |>
  full_join(HDL_CholP2017, by = c("SEQN" = "SEQN")) |>
  full_join(LDL_Tri_CholP2017, by = c("SEQN" = "SEQN")) |>
  full_join(InsulinP2017, by = c("SEQN" = "SEQN")) |>
  full_join(HormonesP2017, by = c("SEQN" = "SEQN"))

# Questionnaire
Questionnarie2011 <- DiabetesQ2011 |>
  full_join(IncomeQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(MedicalCondnsQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(MentalHealthQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(PestisideQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(PhysicalActQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(PrescriptionMedsQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(SleepDisordersQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(SmokingQ2011, by = c("SEQN" = "SEQN")) |>
  full_join(WeightHistoryQ2011, by = c("SEQN" = "SEQN"))

Questionnarie2013 <- DiabetesQ2013 |>
  full_join(IncomeQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(MedicalCondnsQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(MentalHealthQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(PestisideQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(PhysicalActQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(PrescriptionMedsQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(SleepDisordersQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(SmokingQ2013, by = c("SEQN" = "SEQN")) |>
  full_join(WeightHistoryQ2013, by = c("SEQN" = "SEQN"))

Questionnarie2015 <- DiabetesQ2015 |>
  full_join(IncomeQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(MedicalCondnsQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(MentalHealthQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(PestisideQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(PhysicalActQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(PrescriptionMedsQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(SleepDisordersQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(SmokingQ2015, by = c("SEQN" = "SEQN")) |>
  full_join(WeightHistoryQ2015, by = c("SEQN" = "SEQN"))

Questionnarie2017 <- DiabetesQ2017 |>
  full_join(IncomeQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(MedicalCondnsQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(MentalHealthQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(PestisideQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(PhysicalActQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(PrescriptionMedsQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(SleepDisordersQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(SmokingQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(WeightHistoryQ2017, by = c("SEQN" = "SEQN"))

Questionnarie2021 <- DiabetesQ2021 |>
  full_join(IncomeQ2021, by = c("SEQN" = "SEQN")) |>
  full_join(MedicalCondnsQ2021, by = c("SEQN" = "SEQN")) |>
  full_join(MentalHealthQ2021, by = c("SEQN" = "SEQN")) |>
  full_join(PestisideQ2021, by = c("SEQN" = "SEQN")) |>
  full_join(PhysicalActQ2017, by = c("SEQN" = "SEQN")) |>
  full_join(PrescriptionMedsQ2021, by = c("SEQN" = "SEQN")) |>
  full_join(SleepDisordersQ2021, by = c("SEQN" = "SEQN")) |>
  full_join(SmokingQ2021, by = c("SEQN" = "SEQN")) |>
  full_join(WeightHistoryQ2021, by = c("SEQN" = "SEQN"))

QuestionnarieP2017 <- DiabetesQP2017 |>
  full_join(IncomeQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(MedicalCondnsQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(MentalHealthQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(PestisideQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(PhysicalActQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(PrescriptionMedsQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(SleepDisordersQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(SmokingQP2017, by = c("SEQN" = "SEQN")) |>
  full_join(WeightHistoryQP2017, by = c("SEQN" = "SEQN"))
```


#### Merge and Export
```{r}
NHANES2011 <- Demographics2011 |>
  full_join(Examination2011, by = c("SEQN" = "SEQN")) |>
  full_join(Lab2011, by = c("SEQN" = "SEQN")) |>
  full_join(Questionnarie2011, by = c("SEQN" = "SEQN"))


NHANES2013 <- Demographics2013 |>
  full_join(Examination2013, by = c("SEQN" = "SEQN")) |>
  full_join(Lab2013, by = c("SEQN" = "SEQN")) |>
  full_join(Questionnarie2013, by = c("SEQN" = "SEQN"))
  
NHANES2015 <- Demographics2015 |>
  full_join(Examination2015, by = c("SEQN" = "SEQN")) |>
  full_join(Lab2015, by = c("SEQN" = "SEQN")) |>
  full_join(Questionnarie2015, by = c("SEQN" = "SEQN"))
  
NHANES2017 <- Demographics2017 |>
  full_join(Examination2017, by = c("SEQN" = "SEQN")) |>
  full_join(Lab2017, by = c("SEQN" = "SEQN")) |>
  full_join(Questionnarie2017, by = c("SEQN" = "SEQN"))
  
NHANES2021 <- Demographics2021 |>
  full_join(Examination2021, by = c("SEQN" = "SEQN")) |>
  full_join(Lab2021, by = c("SEQN" = "SEQN")) |>
  full_join(Questionnarie2021, by = c("SEQN" = "SEQN"))
  
NHANESP2017 <- DemographicsPP2017 |>
  full_join(ExaminationP2017, by = c("SEQN" = "SEQN")) |>
  full_join(LabP2017, by = c("SEQN" = "SEQN")) |>
  full_join(QuestionnarieP2017, by = c("SEQN" = "SEQN"))

write_xpt(NHANES2011, "NHANES2011.xpt")
write_xpt(NHANES2013, "NHANES2013.xpt")
write_xpt(NHANES2015, "NHANES2015.xpt")
write_xpt(NHANES2017, "NHANES2017.xpt")
write_xpt(NHANES2021, "NHANES2021.xpt")
write_xpt(NHANESP2017, "NHANESP2017.xpt")


```

### Start
```{r}
NHANES2011 <- read_xpt("NHANES2011.xpt")
NHANES2013 <- read_xpt("NHANES2013.xpt") 
NHANES2015 <- read_xpt("NHANES2015.xpt") 
NHANES2017 <- read_xpt("NHANES2017.xpt") 
NHANES2021 <- read_xpt("NHANES2021.xpt") 
NHANESP2017 <- read_xpt("NHANESP2017.xpt") 

sum(dim(NHANES2011), dim(NHANES2013), dim(NHANES2015), dim(NHANES2017), dim(NHANES2021))


```


>>>>>>> 5ac0bc8572beaae8a9c4eaa56fa871a51a2c2a78
